language: node_js
node_js: 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  #- docker-compose -f docker-compose-build.yaml build
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-user manenim/udagram-api-user:v1
  - docker tag udagram-api-feed manenim/udagram-api-feed:v1
  - docker tag udagram-frontend manenim/udagram-frontend:v1
  - docker tag udagram-reverseproxy manenim/udagram-reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push manenim/udagram-api-user:v1
  - docker push manenim/udagram-api-feed:v1
  - docker push manenim/udagram-frontend:v1
  - docker push manenim/udagram-reverseproxy:v1
  
  